'use server';

import { prisma } from '@/lib/prisma';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth-options';

export async function useTool(toolName: string, prompt: string) {
  const session = await getServerSession(authOptions);

  if (!session || !session.user?.email) {
    return { success: false, requireLogin: true, message: 'Please login to use this tool.' };
  }

  try {
    const user = await prisma.user.findUnique({
      where: { email: session.user.email },
    });

    if (!user) {
      return { success: false, requireLogin: true, message: 'User not found.' };
    }

    // Check usage count for this specific tool
    const usageCount = await prisma.toolUsage.count({
      where: { userId: user.id, toolName: toolName }
    });

    const MAX_FREE_TRIALS_PER_TOOL = 3;

    if (usageCount >= MAX_FREE_TRIALS_PER_TOOL) {
      return { success: false, outOfCredits: true, message: `You have exhausted your ${MAX_FREE_TRIALS_PER_TOOL} free trials for this tool.` };
    }

    // Simulate AI Generation Processing Time
    await new Promise(resolve => setTimeout(resolve, 1500));

    let result = '';
    switch (toolName) {
      case 'text-summarizer':
        result = "Here is the summarized version of your text. It has been reduced to capture only the most essential points. (Generated by AI)";
        break;
      case 'idea-validator':
        result = "🔥 Idea Validation Report:\n\nMarket Viability: High (85%)\nCompetitors: 3 main competitors found.\nStrengths: Unique value proposition.\nWeaknesses: High initial acquisition cost.\nVerdict: Worth pursuing.";
        break;
      case 'resume-builder':
        result = "John Doe\nSoftware Engineer\n\n- Optimized AI pipelines using Python.\n- Reduced cloud costs by 40%.\n- Integrated LLMs into SaaS platforms.\n\n(ATS-Optimized Resume Generated by AI)";
        break;
      case 'ai-email-writer':
        result = "Subject: Elevating Your AI Infrastructure\n\nHi there,\n\nI noticed you are scaling your operations. Let's connect this week to discuss how our AI solutions can automate your workflow and cut costs.\n\nBest,\n[Your Name]";
        break;
      default:
        result = "Generated content for " + toolName;
    }

    // Record usage
    await prisma.toolUsage.create({
      data: {
        userId: user.id,
        toolName: toolName,
        prompt: prompt,
        result: result
      }
    });

    return { 
      success: true, 
      result, 
      remainingCredits: MAX_FREE_TRIALS_PER_TOOL - (usageCount + 1)
    };

  } catch (error) {
    console.error("Tool usage error:", error);
    return { success: false, message: 'An internal server error occurred.' };
  }
}
