import React from 'react';
import Link from 'next/link';

export default function DocuMindTerms() {
  return (
    <div className="bg-[#FDFBFE] min-h-screen py-24 px-6 lg:px-12 font-sans relative">
      <div className="max-w-3xl mx-auto relative z-10 bg-white p-12 md:p-16 rounded-[32px] border border-gray-100 shadow-[0_4px_30px_rgba(0,0,0,0.03)]">
        
        <div className="mb-12 border-b border-gray-100 pb-8">
          <Link href="/documind" className="inline-flex items-center gap-2 text-[#7C3AED] text-[14px] font-semibold hover:underline mb-8">
            &larr; Back to DocuMind
          </Link>
          <h1 className="text-[40px] md:text-[48px] font-semibold text-gray-900 leading-tight mb-4" style={{ fontFamily: 'var(--syne), serif' }}>
            Terms and Conditions
          </h1>
          <p className="text-[15px] text-gray-500">Last updated: {new Date().toLocaleDateString()}</p>
        </div>

        <div className="prose prose-purple max-w-none prose-headings:font-serif prose-headings:font-semibold prose-headings:text-gray-900 prose-p:text-gray-600 prose-p:leading-relaxed prose-li:text-gray-600">
          
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing and using the DocuMind service ("Service"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the Service.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            DocuMind provides an AI-powered document intelligence platform that allows users to upload documents (PDFs, text, images) and interact with them via natural language queries, summaries, and generated study materials.
          </p>

          <h2>3. Intellectual Property Rights (Your Data)</h2>
          <p>
            <strong>You own your data.</strong> DocuMind claims no ownership rights over the documents, texts, or images you upload to the Service. 
          </p>
          <ul>
            <li>You retain all copyright and intellectual property rights to your uploaded content.</li>
            <li>You grant DocuMind a limited, strictly necessary license to process your documents solely for the purpose of providing the Service (e.g., parsing, running OCR, generating embeddings, and answering your queries).</li>
            <li>We do <strong>not</strong> use your intellectual property to train our base AI models.</li>
          </ul>

          <h2>4. User Responsibilities and Acceptable Use</h2>
          <p>
            You agree not to use the Service to:
          </p>
          <ul>
            <li>Upload documents that contain illegal, harmful, or explicitly offensive material.</li>
            <li>Upload documents that infringe upon the intellectual property rights, privacy, or copyrights of third parties.</li>
            <li>Attempt to reverse engineer, decompile, or extract the source code or proprietary models powering DocuMind.</li>
            <li>Use the Service to process highly sensitive classified government data, Protected Health Information (PHI) under HIPAA, or Payment Card Industry (PCI) data without explicit Enterprise agreements.</li>
          </ul>

          <h2>5. AI Generation and Accuracy Disclaimer</h2>
          <p>
            DocuMind utilizes advanced artificial intelligence (Large Language Models and Vision-Language Models) to parse documents and generate responses.
          </p>
          <ul>
            <li>While we strive for high accuracy, AI-generated responses may contain errors, hallucinations, or misinterpretations.</li>
            <li>DocuMind is an assistive tool. You must independently verify any critical, legal, financial, or medical information generated by the AI against the original source document.</li>
            <li>DocuMind provides citations to the uploaded document, but is not liable for damages resulting from decisions made based on AI-generated text.</li>
          </ul>

          <h2>6. Subscription and Billing</h2>
          <p>
            DocuMind operates on a freemium model. 
          </p>
          <ul>
            <li><strong>Free Tier:</strong> Limited to 3 documents and 20 messages per month.</li>
            <li><strong>Pro Tier:</strong> Paid monthly or annually. Subscriptions automatically renew unless canceled prior to the billing cycle. You may cancel at any time, and you will retain access to Pro features until the end of your current billing period.</li>
          </ul>

          <h2>7. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your account if you violate these Terms and Conditions. Upon termination, your data will be permanently deleted from our servers in accordance with our Privacy Policy.
          </p>

          <h2>8. Contact</h2>
          <p>
            For any legal inquiries regarding these Terms, please contact legal@documind.ai.
          </p>
        </div>
      </div>
    </div>
  );
}
