import React from 'react';
import Link from 'next/link';

export default function DocuMindPrivacy() {
  return (
    <div className="bg-[#FDFBFE] min-h-screen py-24 px-6 lg:px-12 font-sans relative">
      <div className="max-w-3xl mx-auto relative z-10 bg-white p-12 md:p-16 rounded-[32px] border border-gray-100 shadow-[0_4px_30px_rgba(0,0,0,0.03)]">
        
        <div className="mb-12 border-b border-gray-100 pb-8">
          <Link href="/documind" className="inline-flex items-center gap-2 text-[#7C3AED] text-[14px] font-semibold hover:underline mb-8">
            &larr; Back to DocuMind
          </Link>
          <h1 className="text-[40px] md:text-[48px] font-semibold text-gray-900 leading-tight mb-4" style={{ fontFamily: 'var(--syne), serif' }}>
            Privacy Policy
          </h1>
          <p className="text-[15px] text-gray-500">Last updated: {new Date().toLocaleDateString()}</p>
        </div>

        <div className="prose prose-purple max-w-none prose-headings:font-serif prose-headings:font-semibold prose-headings:text-gray-900 prose-p:text-gray-600 prose-p:leading-relaxed prose-li:text-gray-600">
          
          <div className="bg-purple-50 border border-purple-100 rounded-2xl p-6 mb-10">
            <h3 className="text-[#7C3AED] text-[18px] mb-2 mt-0">Private by Design</h3>
            <p className="text-[14px] text-purple-900 m-0">
              At DocuMind, we believe your documents are your intellectual property. We utilize a self-hosted AI architecture, meaning <strong>your data is never sent to third-party language models like OpenAI or Anthropic.</strong>
            </p>
          </div>

          <h2>1. Information We Collect</h2>
          <p>
            When you use DocuMind, we collect the following types of information:
          </p>
          <ul>
            <li><strong>Account Information:</strong> Name, email address, and authentication credentials.</li>
            <li><strong>Uploaded Documents:</strong> PDFs, textbooks, contracts, and scanned images you upload for analysis.</li>
            <li><strong>Chat History:</strong> The queries you submit and the answers generated by our AI.</li>
          </ul>

          <h2>2. How We Use Your Information</h2>
          <p>
            We use your uploaded documents and chat history strictly to provide the DocuMind service to you. 
          </p>
          <ul>
            <li><strong>Zero Training Policy:</strong> We do not use your personal data, uploaded documents, or chat histories to train, fine-tune, or improve our foundation AI models.</li>
            <li><strong>Service Delivery:</strong> We process your documents through our self-hosted OCR and Language Models solely to answer your explicit queries.</li>
          </ul>

          <h2>3. Data Storage and Security</h2>
          <p>
            We implement SOC-grade security measures to protect your data:
          </p>
          <ul>
            <li><strong>Data Isolation:</strong> Your documents and vector embeddings are logically segregated in our databases using Row-Level Security (RLS). No other user can access your data.</li>
            <li><strong>Encryption:</strong> All files are encrypted at rest using AES-256 encryption and in transit using TLS 1.3.</li>
            <li><strong>Data Retention & Deletion:</strong> You have full control over your data. When you delete a document or your account, we perform a hard delete across our storage buckets and vector databases immediately. No backups are retained beyond standard 30-day disaster recovery cycles.</li>
          </ul>

          <h2>4. Multilingual OCR and Processing</h2>
          <p>
            To process handwritten and multilingual documents (including Tamil, Hindi, Telugu, etc.), we utilize proprietary and open-weights Vision-Language Models hosted securely within our own Virtual Private Cloud (VPC). Your images never leave our secure environment.
          </p>

          <h2>5. Third-Party Sharing</h2>
          <p>
            We do not sell, rent, or share your personal data or uploaded documents with any third parties for marketing or external AI training purposes. We only share data with essential infrastructure providers (e.g., our cloud hosting provider, AWS) under strict Data Processing Agreements.
          </p>

          <h2>6. Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy or our security practices, please contact our Data Protection Officer at privacy@documind.ai.
          </p>
        </div>
      </div>
    </div>
  );
}
